name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project"

  test:
    runs-on: ubuntu-latest
    needs: build  # Depends on the build job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Display a message
      run: echo "Hello, this is a message 1 displayed on Ubuntu!"

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Depends on the test job
    steps:
      - run: echo "Deploying the project"
